default: &default
  framework: torch
#  rollout_fragment_length: 200
  model:
    custom_model: adaptive_multihead_network
  siamese:
    use_siamese: true
    training_batch_size: 52
    buffer_size: 520
    update_frequency: 2000
    update_steps: 3
    embedding_size: 512
    loss_margin: 10000000

  buffer_options:
    siamese_num_clusters: 50
    num_samples_to_recluster: 4000

    prioritized_replay: true
    centralised_buffer: true
    global_size: 1000000
    priority_id: td_errors
    priority_lower_limit: 0
    priority_aggregation_fn: np.mean
    prioritization_alpha: !!float 0.6
    prioritization_importance_beta: !!float 0.4
    prioritization_epsilon: !!float 1e-06
    cluster_size: null
    cluster_prioritisation_strategy: sum
    cluster_level_weighting: true
    clustering_xi: 4
    prioritized_drop_probability: 0
    global_distribution_matching: false
    stationarity_window_size: null
    stationarity_smoothing_factor: 1
    max_age_window: null
  clustering_options:
      clustering_scheme:
        - How_Well
      clustering_scheme_options: {}
      cluster_selection_policy: min
      cluster_with_episode_type: false
      cluster_overview_size: 1
      collect_cluster_metrics: true
      ratio_of_samples_from_unclustered_buffer: 0

GraphDrive-Hard:
  <<: *default

GraphDrive-Medium:
  <<: *default

GraphDrive-Easy:
  <<: *default

Ant-v4:
  <<: *default

HalfCheetah-v4:
  <<: *default

Humanoid-v4:
  <<: *default

Walker2d-v4:
  <<: *default

Swimmer-v4:
  <<: *default

Hopper-v4:
  <<: *default

